services:
  - type: web
    name: naukaair
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /login
    envVars:
      - key: NODE_ENV
        value: production
